{% set version = "1.5" %}

package:
  name: proj-data
  version: {{ version }}

source:
  url: http://download.osgeo.org/proj/proj-data-{{ version }}.zip
  sha256: c346f53f4af8b17de166819dbb98372a937de1fc487a4c4013f40e76678a3202
  folder: data

build:
  number: 0
  noarch: generic

requirements:
  run:
    - proj >=7.0.0

test:
  commands:
    - test -f $PREFIX/share/proj/ca_nrc_ntv1_can.tif
    - echo -111 50 | cs2cs +proj=latlong +ellps=clrk66 +nadgrids=ca_nrc_ntv1_can.tif +to +proj=latlong +ellps=GRS80 +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975

about:
  home: https://github.com/OSGeo/proj-data
  license: Public domain | X/MIT | BSD-2/3/4-Clause | CC0 | CC-BY (v3.0 or later) | CC-BY-SA (v3.0 or later)
  license_family: OTHER
  # Each data source has a *README.txt file with the license info, that is
  # copied with the datum files. The following CSV file is a summary.
  license_file: copyright_and_licenses.csv
  summary: Data for Cartographic Projections and Coordinate Transformations Library

extra:
  recipe-maintainers:
    - hobu
    - ocefpaf
    - snowman2
    - xylar
