{% set version = "1.23" %}

package:
  name: proj-data
  version: {{ version }}

source:
  url: http://download.osgeo.org/proj/proj-data-{{ version }}.tar.gz
  sha256: 1055630cac3d830b794b48af3ca8c9dd88f4d46ef5dc51c270e0a416b3d1fa1c
  folder: data


build:
  noarch: generic
  number: 0

requirements:
  run:
    - __unix                          # [unix]
    - __win                           # [win]
    - proj >=7.0.0

test:
  commands:
    - test -f $PREFIX/share/proj/ca_nrc_ntv1_can.tif  # [unix]
    - if not exist %LIBRARY_PREFIX%\\share\\proj\\ca_nrc_ntv1_can.tif exit 1  # [win]
    - echo -111 50 | cs2cs +proj=latlong +ellps=clrk66 +nadgrids=ca_nrc_ntv1_can.tif +to +proj=latlong +ellps=GRS80 +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975

about:
  home: https://github.com/OSGeo/proj-data
  license: Public domain | X/MIT | BSD-2/3/4-Clause | CC0 | CC-BY (v3.0 or later) | CC-BY-SA (v3.0 or later)
  license_family: OTHER
  # Each data source has a *README.txt file with the license info, that is
  # copied with the datum files. The following CSV file is a summary.
  license_file: data/copyright_and_licenses.csv
  summary: Data for Cartographic Projections and Coordinate Transformations Library
  dev_url: https://github.com/OSGeo/proj-data
  doc_url: https://github.com/OSGeo/PROJ-data/blob/master/README.DATA

extra:
  recipe-maintainers:
    - hobu
    - ocefpaf
    - snowman2
    - xylar
